Motorsazan.CMMS.Client/Controllers/MachineManagementController.cs
using Motorsazan.CMMS.Client.Api;
using Motorsazan.CMMS.Client.Filters;
using Motorsazan.CMMS.Shared.Models.Input.Inspection;
using Motorsazan.CMMS.Shared.Models.Input.MachineManagement;
using Motorsazan.CMMS.Shared.Models.Output.Inspection;
using Motorsazan.CMMS.Shared.Utilities;
using System;
using System.Net.Mime;
using System.Web.Mvc;

namespace Motorsazan.CMMS.Client.Controllers
{
    public class MachineManagementController: BaseController
    {
        public ActionResult AddMachineElectricalInfo(InputAddMachineElectricalInfo values)
        {
            var token = GetUserToken();

            var apiResult = ApiList.AddMachineElectricalInfo(values, token);
            return Content(apiResult);
        }

        public ActionResult RemoveMachineElectricalInfoByRecordId(InputRemoveMachineElectricalInfoByRecordId input)
        {
            var token = GetUserToken();

            var apiResult = ApiList.RemoveMachineElectricalInfoByRecordId(input, token);
            return Content(apiResult);
        }

        public ActionResult RegisterOilAndLubrication(InputRegisterOilAndLubrication values)
        {
            var token = GetUserToken();

            var apiResult = ApiList.RegisterOilAndLubrication(values, token);
            return Content(apiResult);
        }

        public ActionResult RemoveMachineOilAndLubricationInfoByRecordId(
            InputRemoveMachineOilAndLubricationInfoByRecordId values)
        {
            var token = GetUserToken();

            var apiResult = ApiList.RemoveMachineOilAndLubricationInfoByRecordId(values, token);
            return Content(apiResult);
        }


        public ActionResult EditMachineBuiltInfo(InputEditMachineBuiltInfo input, string importPersianDate)
        {
            var token = GetUserToken();
            input.ImportDate = Tools.ConvertToLatinDate(importPersianDate);
            var apiResult = ApiList.EditMachineBuiltInfo(input, token);
            return Content(apiResult);
        }

        public ActionResult FilterDepartmentHasMachineCombo()
        {
            const string partialViewUrl = "~/Views/MachineManagement/FilterForm/filterDepartmentHasMachineCombo.cshtml";

            var departmentListDataSource = ApiList.GetMainDepartmentListHasMachine();


            var allDepartment = new OutputGetMainDepartmentListHasMachine {DepartmentId = 0, Title = "همه"};

            var dataSource = Tools.PrependGetAllItemToArray(departmentListDataSource, allDepartment);


            return PartialView(partialViewUrl, dataSource);
        }

        public ActionResult FilterSubDepartmentHasMachineCombo(
            InputGetSubDepartmentListHasMachineByMainDepartmentId input)
        {
            const string partialViewUrl =
                "~/Views/MachineManagement/FilterForm/FilterSubDepartmentHasMachineCombo.cshtml";

            var subDepartmentListDataSource = ApiList.GetSubDepartmentListHasMachineByMainDepartmentId(input);

            return PartialView(partialViewUrl, subDepartmentListDataSource);
        }


        public ActionResult MachineProducerTabContent(InputGetMachineBuiltInfo input)
        {
            var apiResult = ApiList.GetMachineBuiltInfo(input);
            const string partialViewUrl = "~/Views/MachineManagement/MachineProducer/AddForm.cshtml";
            return PartialView(partialViewUrl, apiResult);
        }

        public ActionResult ShowOilAndLubricationModal(long machineId)
        {
            ViewBag.MachineId = machineId;
            const string partialViewUrl = "~/Views/MachineManagement/AddOilAndLubrication/AddForm.cshtml";
            return PartialView(partialViewUrl);
        }

        [AccessToEventValidation(EventCode = "006", FormCode = "002")]

        public ActionResult ShowElectricalModal(InputGetMachineInfoByMachineId input)
        {
            ViewBag.MachineId = input.MachineId;
            var dataSource = ApiList.GetMachineInfoByMachineId(input);

            const string partialViewUrl = "~/Views/MachineManagement/AddFormMachineBaseInfo/AddForm.cshtml";
            return PartialView(partialViewUrl, dataSource);
        }


        public ActionResult MachineOilTabContentGrid(InputGetMachineOilAndLubricationInfo input)
        {
            var dataSource = ApiList.GetMachineOilAndLubricationInfo(input);
            var partialUrl = "~/Views/MachineManagement/AddOilAndLubrication/MachineOilTabContentGrid.cshtml";
            return PartialView(partialUrl, dataSource);
        }

        public ActionResult MachineElectricalTabContent(InputGetMachineInfoByMachineId input)
        {
            ViewBag.MachineId = input.MachineId;
            var partialUrl = "~/Views/MachineManagement/AddFormMachineBaseInfo/MachineElectricalTabContent.cshtml";
            return PartialView(partialUrl);
        }

        public ActionResult MachineElectricalTabContentGrid(InputGetMachineElectricalInfo input)
        {
            var dataSource = ApiList.GetMachineElectricalInfo(input);
            var partialUrl = "~/Views/MachineManagement/AddFormMachineBaseInfo/MachineElectricalTabContentGrid.cshtml";
            return PartialView(partialUrl, dataSource);
        }

        public ActionResult AddFormCharacteristicCombo()
        {
            const string partialViewUrl =
                "~/Views/MachineManagement/AddFormMachineBaseInfo/AddFormCharacteristicComboPartial.cshtml";
            var source = ApiList.GetCharacteristicList();
            return PartialView(partialViewUrl, source);
        }

        public ActionResult AddFormRpmlistCombo()
        {
            const string partialViewUrl =
                "~/Views/MachineManagement/AddFormMachineBaseInfo/AddFormRpmListComboPartial.cshtml";
            var source = ApiList.GetRpmList();
            return PartialView(partialViewUrl, source);
        }

        public ActionResult AddFormVoltageListCombo()
        {
            const string partialViewUrl =
                "~/Views/MachineManagement/AddFormMachineBaseInfo/AddFormVoltageListComboPartial.cshtml";
            var source = ApiList.GetVoltageList();
            return PartialView(partialViewUrl, source);
        }

        [AccessToFormValidation(FormCode = "002")]
        public ActionResult Index() => View();


        #region StartGrid

        public ActionResult MachineManagementGrid(InputGetTopMachineListByCondition input)
        {
            const string partialViewUrl = "~/Views/MachineManagement/MachinesGrid/MachineManagementGrid.cshtml";

            var machinesDataSource = ApiList.GetTopMachineListByCondition(input);

            return PartialView(partialViewUrl, machinesDataSource);
        }

        public ActionResult MachinesGridDetailRow(long machineId, string machineName, string machineLevelName)
        {
            const string partialViewUrl = "~/Views/MachineManagement/MachinesGrid/MachinesGridDetailRow.cshtml";

            ViewData["MachineId"] = machineId;
            ViewData["MachineName"] = machineName;
            ViewData["MachineLevelName"] = machineLevelName;

            return PartialView(partialViewUrl);
        }

        #endregion StartGrid


        #region ShowSubMachineTree

        public ActionResult SubMachineTreeModal(InputGetHierarchicalMachineList input)
        {
            const string partialViewUrl = "~/Views/MachineManagement/ShowAllSubMachine/SubMachineTreeModal.cshtml";

            ViewBag.MachineTopParentId = input.MachineTopParentId;

            return PartialView(partialViewUrl);
        }

        public ActionResult SubMachineTree(InputGetHierarchicalMachineList input)
        {
            const string partialViewUrl = "~/Views/MachineManagement/ShowAllSubMachine/SubMachineTree.cshtml";

            ViewBag.Data = input.MachineTopParentId;

            var subMachineDataSource = ApiList.GetHierarchicalMachineList(input);

            return PartialView(partialViewUrl, subMachineDataSource);
        }

        #endregion ShowSubMachineTree


        #region AddSubMahcine

        [AccessToEventValidation(EventCode = "002", FormCode = "002")]
        public ActionResult AddSubMachine(long topMachineId)
        {
            const string partialViewUrl = "~/Views/MachineManagement/AddSubMachine/AddForm.cshtml";

            ViewData["MachineTopParentId"] = topMachineId;

            return PartialView(partialViewUrl);
        }

        public ActionResult AddSubMachineTreeList(InputGetHierarchicalMachineList input)
        {
            const string partialViewUrl = "~/Views/MachineManagement/AddSubMachine/AddSubMachineTreeList.cshtml";

            ViewBag.Data = input.MachineTopParentId;

            var subMachineTreeListDataSource = ApiList.GetHierarchicalMachineList(input);

            return PartialView(partialViewUrl, subMachineTreeListDataSource);
        }

        [AccessToEventValidation(EventCode = "002", FormCode = "002")]
        public string AddNewSubMachine(InputAddSubMachine input)
        {
            var token = GetUserToken();
            input.UserId = GetCurrentUser().UserID;

            var addResult = ApiList.AddSubMachine(input, token);
            return addResult;
        }

        #endregion AddSubMahcine


        #region AddMachineDocument

        [AccessToEventValidation(EventCode = "003", FormCode = "002")]
        public ActionResult AddMachineDocument(long topMachineId)
        {
            const string partialViewUrl = "~/Views/MachineManagement/AddDocument/AddForm.cshtml";

            ViewData["MachineTopParentId"] = topMachineId;

            return PartialView(partialViewUrl);
        }

        public ActionResult AddMachineDocumentTreeList(InputGetHierarchicalMachineList input)
        {
            const string partialViewUrl = "~/Views/MachineManagement/AddDocument/AddSubMachineTreeList.cshtml";

            ViewBag.Data = input.MachineTopParentId;

            var machineDocumentDataSource = ApiList.GetHierarchicalMachineList(input);

Motorsazan.CMMS.Client/Views/MachineManagement/AddMachineSparePart/AddForm.cshtml
<section class="app__section">
    <div id="addFormSparePartFormDesign" class="app__section__body">

        <div class="row">
            <div class="col-xs-12 col-md-6 col-lg-6">
                <div class="app__form-item">
                    <div id="addSparePartSubMachineTreeDesign">
                        <label class="app__form-label">
                            انتخاب دستگاه
                        </label>
                        <div id="addSparePartSubMachineTreeParent">
                            @{
                                var machineId = (long) ViewData["MachineTopParentId"];
                                Html.RenderAction("AddSparePartSubMachineTreeList", "MachineManagement", new {MachineTopParentId = machineId});
                            }
                        </div>
                        <div class="app__form-error app__hide" id="addSparePartSubMachineTreeError">
                            نام دستگاه وارد نشده است
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-md-6 col-lg-6 pull-left">

                <div class="col-xs-12 col-md-12">
                    <div class="app__form-item">
                        <label class="app__form-label">
                            انتخاب انبار
                        </label>
                        <div id="addFormStoreListForSparePartComboParent">
                            @Html.Action("AddFormGetStoreListForSparePart", "MachineManagement")
                        </div>
                        <div class="app__form-error app__hide" id="addFormStoreListForSparePartComboError">
                            انبار انتخاب نشده است
                        </div>
                    </div>
                </div>

                <div class="col-xs-12 col-md-12">
                    <div class="app__form-item">
                        <label class="app__form-label">
                            انتخاب قطعه
                        </label>
                        <div id="addFormStockComboParent">
                            @{ Html.RenderAction("SundryModalStockComboByRackCode", "MachineManagement"); }
                        </div>
                        <div class="app__form-error app__hide" id="addFormStockComboError">
                            قطعه انتخاب نشده است
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-xs-12 col-md-6">
                        <div class="app__form-item">
                            <label class="app__form-label">
                                درجه اهمیت
                            </label>
                            <div id="addStocksImportanceComboParent">
                                @{ Html.RenderPartial("~/Views/MachineManagement/AddMachineSparePart/AddStocksImportance.cshtml"); }
                            </div>
                            <div class="app__form-error app__hide" id="addStocksImportanceComboError">
                                درجه اهمیت قطعه انتخاب نشده است
                            </div>
                        </div>
                    </div>

                    <div class="col-xs-12 col-md-6">
                        <div class="app__form-item">
                            <label class="app__form-label">
                                نوع تامین
                            </label>
                            <div id="addStockSupplyTypeComboParent">
                                @{ Html.RenderPartial("~/Views/MachineManagement/AddMachineSparePart/AddStockSupplyType.cshtml"); }
                            </div>
                            <div class="app__form-error app__hide" id="addStockSupplyTypeComboError">
                                نوع تامین قطعه انتخاب نشده است
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-xs-12 col-md-6">
                        <div class="app__form-item">
                            <label class="app__form-label">
                                تاریخ
                            </label>
                            <input type="text" class="app__form-datepicker"
                                   id="addStocksDate"
                                   placeholder="تاریخ را انتخاب نمایید"
                                   data-mddatetimepicker="true"
                                   data-englishnumber="true"
                                   data-targetdateselector="#addStocksDate"/>
                            <div class="app__form-error app__hide" id="addStocksDateError">
                                تاریخ انتخاب نشده است
                            </div>
                        </div>
                    </div>

                    <div class="col-xs-12 col-md-6">
                        <div class="app__form-item">
                            <label class="app__form-label">
                                مشخصات فنی قطعه در کاتالوگ
                            </label>
                            @Html.DevExpress().TextBox(settings =>
                            {
                                settings.Name = "addStockTechnicalCharacteristicsCatalog";
                                settings.Properties.NullText = "مشخصات فنی قطعه";
                                settings.Properties.ClientSideEvents.ValueChanged =
                                    "motorsazanClient.machineManagement.handleAddStockTechnicalCharacteristicsCatalogValueChanged";
                            }).GetHtml()
                            <div class="app__form-error app__hide"
                                 id="addStockTechnicalCharacteristicsCatalogError">
                                مشخصات فنی قطعه انتخاب نشده است
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-xs-12 col-sm-4 col-md-3 pull-left">
                        <div class="app__form-item app__form-item--action">
                            @Html.DevExpress().Button(settings =>
                            {
                                settings.Name = "addDocumentSaveBtn";
                                settings.Text = "ثبت";
                                settings.UseSubmitBehavior = false;
                                settings.EnableClientSideAPI = true;
                                settings.Styles.CssPostfix = "add-form__btn";
                                settings.Width = Unit.Percentage(100);
                                settings.ClientSideEvents.Click =
                                    "motorsazanClient.machineManagement.handleAddSubMachineSparePartSaveBtnClick";
                            }).GetHtml()
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="app__section__body">
        <form class="app__grid-wrapper" id="machineSparePartDataGridParent">
            @{ Html.RenderPartial("~/Views/MachineManagement/AddMachineSparePart/MachineSparePartGrid.cshtml"); }
        </form>
    </div>

</section>

Motorsazan.CMMS.Client/Views/MachineManagement/AddMachineSparePart/AddFormDocumentToSparePartModal.cshtml
<section class="app__section">
    <div id="addFormSparePartFormDocumentDesign" class="app__section__body">
        <div class="row">
            <div class="col-xs-12 col-md-6 col-lg-6">
                <div class="app__form-item">
                    <label class="app__form-label">
                        مشخصات الکتریکی
                    </label>
                    <div id="addMachineSparePartDocumentElectricalSpecificationTextBoxParent">
                        @Html.DevExpress().TextBox(settings =>
                        {
                            settings.Name = "addMachineSparePartDocumentElectricalSpecificationTextBox";
                            settings.Width = Unit.Percentage(100);
                            settings.Properties.ClientSideEvents.ValueChanged =
                                "motorsazanClient.machineManagement.handleAddMachineSparePartDocumentElectricalSpecificationTextBoxValueChanged";
                        }).GetHtml()
                    </div>
                    <div class="app__form-error app__hide"
                         id="addMachineSparePartDocumentElectricalSpecificationTextBoxError">
                        مشخصات الکتریکی وارد نشده است
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-md-6 col-lg-6">
                <div class="app__form-item">
                    <label class="app__form-label">
                        مشخصات مکانیکی
                    </label>
                    <div id="addMachineSparePartDocumentMechanicalSpecificationTextBoxParent">
                        @Html.DevExpress().TextBox(settings =>
                        {
                            settings.Name = "addMachineSparePartDocumentMechanicalSpecificationTextBox";
                            settings.Width = Unit.Percentage(100);
                            settings.Properties.ClientSideEvents.ValueChanged =
                                "motorsazanClient.machineManagement.handleAddMachineSparePartDocumentMechanicalSpecificationTextBoxValueChanged";
                        }).GetHtml()
                    </div>
                    <div class="app__form-error app__hide"
                         id="addMachineSparePartDocumentMechanicalSpecificationTextBoxError">
                        مشخصات مکانیکی وارد نشده است
                    </div>
                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-xs-12 col-md-6" id="machineSparePartAttachmentUploaderDesign">
                <div class="app__form-item" id="machineSparePartAttachmentUploaderParent">
                    <label class="app__form-label">
                        فایل ضمیمه
                    </label>
                    <div id="machineSparePartAttachmentUploader"></div>
                    <div class="app__form-error app__hide" id="machineSparePartAttachmentUploaderError">
                        فایل ضمیمه انتخاب نشده است
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-md-6 col-lg-6 pull-left">
                <div class="col-xs-12 col-md-12 col-lg-12">
                    <div class="app__form-item">
                        <label class="app__form-label">
                            شرکت سازنده
                        </label>
                        <div id="addMachineSparePartDocumentMadeInCompanyTextBoxParent">
                            @Html.DevExpress().TextBox(settings =>
                            {
                                settings.Name = "addMachineSparePartDocumentMadeInCompanyTextBox";
                                settings.Width = Unit.Percentage(100);
                                settings.Properties.ClientSideEvents.ValueChanged =
                                    "motorsazanClient.machineManagement.handleAddMachineSparePartDocumentMadeInCompanyTextBoxValueChanged";
                            }).GetHtml()
                        </div>
                        <div class="app__form-error app__hide"
                             id="addMachineSparePartDocumentMadeInCompanyTextBoxError">
                            شرکت سازنده وارد نشده است
                        </div>
                    </div>
                </div>

                <div class="col-xs-12 col-md-12 col-lg-12">
                    <div class="app__form-item">
                        <label class="app__form-label">
                            توضیحات
                        </label>
                        <div id="addMachineSparePartDocumentDescriptionParent">
                            @Html.DevExpress().Memo(settings =>
                            {
                                settings.Name = "addMachineSparePartDocumentDescription";
                                settings.Properties.NullText = "توضیحات";
                                settings.Properties.ClientSideEvents.ValueChanged =
                                    "motorsazanClient.machineManagement.handleAddMachineSparePartDocumentDescriptionValueChanged";
                            }).GetHtml()

                        </div>
                        <div class="app__form-error app__hide" id="addMachineSparePartDocumentDescriptionError">
                            توضیحات وارد نشده است
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-xs-6 col-md-4 col-lg-3 filter-form__action-wrapper pull-left">
                        <div class="app__form-item app__form-item--action">
                            @Html.DevExpress().Button(settings =>
                            {
                                settings.Name = "addMachineSparePartDocumentSaveBtn";
                                settings.Text = "ثبت";
                                settings.UseSubmitBehavior = false;
                                settings.EnableClientSideAPI = true;
                                settings.Styles.CssPostfix = "add-form__btn";
                                settings.Width = Unit.Percentage(100);
                                settings.ClientSideEvents.Click =
                                    "motorsazanClient.machineManagement.handleAddMachineSparePartDocumentSaveBtnClick";
                            }).GetHtml()
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </div>


    <div class="app__section__body">
        <form class="app__grid-wrapper" id="machineSparePartDocumentGridParent">
            @{ Html.RenderAction("GetMachineSparePartDocumentList", "MachineManagement", new { model = ViewData["MachineSparePartId"] }); }
        </form>
    </div>
</section>

Motorsazan.CMMS.Client/Views/MachineManagement/AddMachineSparePart/AddFormSparePartSubMachineTreeList.cshtml
@model IEnumerable<Motorsazan.CMMS.Shared.Models.Output.MachineManagement.OutputGetHierarchicalMachineList>

@Html.DevExpress().TreeList(
    settings =>
    {
        settings.Name = "addSparePartSubMachineTree";
        settings.CallbackRouteValues = new { Controller = "MachineManagement", Action = "AddSparePartSubMachineTreeList" };
        settings.Width = Unit.Percentage(100);

        settings.ClientSideEvents.BeginCallback = "motorsazanClient.machineManagement.onMachineSparePartTreeBeginCallback";

        settings.ClientSideEvents.FocusedNodeChanged = "motorsazanClient.machineManagement.getMachineSparePartTreeSelectedNode";

        settings.KeyFieldName = "MachineId";
        settings.ParentFieldName = "MachineParentId";

        settings.SettingsPager.Visible = true;
        settings.SettingsBehavior.AllowFocusedNode = true;

        settings.SettingsBehavior.FocusNodeOnLoad = false;

        settings.Theme = "Aqua";
        settings.Styles.Header.CssClass = "tree-header-style";

        settings.Settings.VerticalScrollBarMode = ScrollBarMode.Auto;
        settings.Settings.ScrollableHeight = 350;

        settings.Settings.HorizontalScrollBarMode = ScrollBarMode.Hidden;

        settings.SettingsBehavior.FocusNodeOnLoad = false;

        settings.Columns.Add(m =>
        {
            m.FieldName = "MachineName";
            m.Caption = "نام دستگاه";
            m.Width = Unit.Percentage(80);

            m.CellStyle.Wrap = DefaultBoolean.True;

            m.ColumnType = MVCxTreeListColumnType.TextBox;
            var textProperties = m.PropertiesEdit as TextEditProperties;

            textProperties.Width = System.Web.UI.WebControls.Unit.Percentage(100);
        });

        settings.Columns.Add(m =>
        {
            m.FieldName = "OldMachineCode";
            m.Caption = "کد دستگاه";
            m.Width = Unit.Percentage(20);
        });

        settings.SettingsBehavior.ExpandCollapseAction = TreeListExpandCollapseAction.NodeDblClick;
        settings.PreRender = (sender, e) =>
        {
            MVCxTreeList treeList = (MVCxTreeList)sender;
            treeList.ExpandAll();
        };
    }).Bind(Model).GetHtml()

Motorsazan.CMMS.Client/Views/MachineManagement/AddMachineSparePart/AddFormStoreListForSparePartCombo.cshtml
@model Motorsazan.CMMS.Shared.Models.Output.MachineManagement.OutputGetStoreListForSparePart[]

@Html.DevExpress().ComboBox(
    settings =>
    {
        settings.Name = "addFormStoreListForSparePartCombo";
        settings.CallbackRouteValues = new { Controller = "MachineManagement", Action = "AddFormGetStoreListForSparePart" };
        settings.Width = Unit.Percentage(100);
        settings.Properties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.None;
        settings.Properties.NullText = "انتخاب انبار";
        settings.SelectedIndex = 0;
        settings.Properties.CallbackPageSize = 100;
        settings.Properties.IncrementalFilteringMode = IncrementalFilteringMode.None;
        settings.Properties.IncrementalFilteringDelay = 200;
        settings.SettingsLoadingPanel.Text = "در حال دریافت اطلاعات";
        settings.Properties.ValueField = "RackCode";
        settings.Properties.ValueType = typeof(int);

        settings.Properties.TextFormatString = "{0} {1}";

        settings.Properties.Columns.Add("StoreName", "نام انبار");
        settings.Properties.Columns.Add("StoreCode", "کد انبار");

        settings.Properties.ClientSideEvents.SelectedIndexChanged =
            "motorsazanClient.machineManagement.handleAddFormStoreListForSparePartComboSelectedIndexChanged";
    }).BindList(Model).GetHtml()

Motorsazan.CMMS.Client/Views/MachineManagement/AddMachineSparePart/AddStockSupplyType.cshtml
@Html.DevExpress().ComboBox(
    settings =>
    {
        settings.Name = "addStockSupplyTypeCombo";
        settings.Width = Unit.Percentage(100);
        settings.Properties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.None;
        settings.Properties.NullText = "نوع تامین قطعه انتخاب نمایید";
        settings.SelectedIndex = -1;
        settings.Properties.CallbackPageSize = 100;
        settings.Properties.IncrementalFilteringMode = IncrementalFilteringMode.Contains;
        settings.Properties.IncrementalFilteringDelay = 200;
        settings.SettingsLoadingPanel.Text = "در حال دریافت اطلاعات";

        settings.Properties.Items.Add("خارجی", false);
        settings.Properties.Items.Add("داخلی", true);

        settings.Properties.ClientSideEvents.SelectedIndexChanged =
            "motorsazanClient.machineManagement.handleAddStockSupplyTypeComboSelectedIndexChanged";

    }).GetHtml()

Motorsazan.CMMS.Client/Views/MachineManagement/AddMachineSparePart/AddStocksImportance.cshtml
@Html.DevExpress().ComboBox(
    settings =>
    {
        settings.Name = "addStocksImportanceCombo";
        settings.Width = Unit.Percentage(100);
        settings.Properties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.None;
        settings.Properties.NullText = "درجه اهمیت قطعه انتخاب نمایید";
        settings.SelectedIndex = -1;
        settings.Properties.CallbackPageSize = 100;
        settings.Properties.IncrementalFilteringMode = IncrementalFilteringMode.Contains;
        settings.Properties.IncrementalFilteringDelay = 200;
        settings.SettingsLoadingPanel.Text = "در حال دریافت اطلاعات";

        settings.Properties.Items.Add("عمومی", false);
        settings.Properties.Items.Add("انحصاری", true);

        settings.Properties.ClientSideEvents.SelectedIndexChanged =
            "motorsazanClient.machineManagement.handleAddStocksImportanceComboSelectedIndexChanged";

    }).GetHtml()