Motorsazan.CMMS.Client/Controllers/PreventiveMaintenancesSchedulingReportController.cs
using Motorsazan.CMMS.Client.Api;
using Motorsazan.CMMS.Shared.Enums;
using Motorsazan.CMMS.Shared.Models.Input.Inspection;
using Motorsazan.CMMS.Shared.Models.Input.PreventiveMaintenancesSchedulingReport;
using Motorsazan.CMMS.Shared.Models.Output.Inspection;
using Motorsazan.CMMS.Shared.Models.Output.ProductiveWorkOrder;
using Motorsazan.CMMS.Shared.Utilities;
using System.Web.Mvc;

namespace Motorsazan.CMMS.Client.Controllers
{
    public class PreventiveMaintenancesSchedulingReportController: BaseController
    {
        public ActionResult FilterFormMainDepartmentCombo()
        {
            const string partialViewUrl =
                "~/Views/PreventiveMaintenancesSchedulingReport/FilterForm/FilterFormMainDepartmentCombo.cshtml";
            var token = GetUserToken();
            var departmentList = ApiList.GetAllMainDepartment(token);


            return PartialView(partialViewUrl, departmentList);
        }

        public ActionResult FilterFormSubDepartmentCombo(InputGetSubDepartmentListHasMachineByMainDepartmentId value)
        {
            const string partialViewUrl =
                "~/Views/PreventiveMaintenancesSchedulingReport/FilterForm/FilterFormSubDepartmentCombo.cshtml";
            var subDepartmentList = ApiList.GetSubDepartmentListHasMachineByMainDepartmentId(value);

            var allsubDepartmentList =
                new OutputGetSubDepartmentListHasMachineByMainDepartmentId { DepartmentId = 0, Title = "همه خطوط" };
            var dataSource = Tools.PrependGetAllItemToArray(subDepartmentList, allsubDepartmentList);

            return PartialView(partialViewUrl, dataSource);
        }

        public ActionResult FilterFormMaintenanceGroupCombo()
        {
            const string partialViewUrl =
                "~/Views/PreventiveMaintenancesSchedulingReport/FilterForm/FilterFormMaintenanceGroupCombo.cshtml";


            var maintenanceGroupList = ApiList.GetMaintenanceGroupList();

            var allMaintenanceGroupList =
                new OutputGetMaintenanceGroupList {MaintenanceGroupId = 0, MaintenanceGroupName = "همه گروه ها"};

            var dataSource = Tools.PrependGetAllItemToArray(maintenanceGroupList, allMaintenanceGroupList);

            return PartialView(partialViewUrl, dataSource);
        }

        public OutputGetSubDepartmentListByMainDepartmentId[] GetSubDepartmentList(
            InputGetSubDepartmentListByMainDepartmentId values) =>
            ApiList.GetSubDepartmentListByMainDepartmentId(values);

        public static OutputGetMaintenanceGroupList[] GetWorkOrderMaintenanceGroupList() =>
            ApiList.GetMaintenanceGroupList();

        public ActionResult Grid(InputGetPreventiveMaintenanceSchedulingReportByCondition input,
            string startShamsiDate, string endShamsiDate, DatePeriodType dateType = DatePeriodType.CurrentDay)
        {
            const string partialViewUrl = "~/Views/PreventiveMaintenancesSchedulingReport/Grid/Grid.cshtml";

            var token = GetUserToken();

            (input.StartDate, input.EndDate) = Tools.NormalizeDates(startShamsiDate, endShamsiDate, dateType);

            var dataSourc = ApiList.GetPreventiveMaintenanceSchedulingReportByCondition(input, token);

            return PartialView(partialViewUrl, dataSourc);
        }

        public ActionResult Index() => View();
    }
}

Motorsazan.CMMS.Client/Views/PreventiveMaintenancesSchedulingReport/FilterForm/FilterForm.cshtml
<div class="filter-form filter-form--big">
    <div class="row">
        <div class="col-xs-12 col-md-4" id="filterFormMainDepartmentComboGrandParent">
            <div class="app__form-item">
                <label class="app__form-label">
                    امور
                </label>
                <div id="filterFormMainDepartmentComboParent">
                    @{ Html.RenderAction("FilterFormMainDepartmentCombo", "PreventiveMaintenancesSchedulingReport");}
                </div>
                <div class="app__form-error app__hide" id="filterFormMainDepartmentComboError">
                    امور انتخاب نشده است
                </div>
            </div>
        </div>

        <div class="col-xs-12 col-md-4" id="filterFormSubDepartmentComboGrandParent">
            <div class="app__form-item">
                <label class="app__form-label">
                    خط
                </label>
                <div id="filterFormSubDepartmentComboParent">
                    @{ Html.RenderAction("FilterFormSubDepartmentCombo", "PreventiveMaintenancesSchedulingReport");}
                </div>
                <div class="app__form-error app__hide" id="filterFormSubDepartmentComboError">
                    خط انتخاب نشده است
                </div>
            </div>
        </div>



        <div class="col-xs-12 col-md-4">
            <div class="app__form-item">
                <label class="app__form-label">
                    گروه تعمیراتی
                </label>
                <div id="filterFormMaintenanceGroupComboParent">
                    @{ Html.RenderAction("FilterFormMaintenanceGroupCombo", "PreventiveMaintenancesSchedulingReport");}
                </div>
                <div class="app__form-error app__hide" id="filterFormMaintenanceComboError">
                    گروه تعمیراتی انتخاب نشده است
                </div>
            </div>
        </div>

        <div class="col-xs-12 col-md-4" id="filterFormDateComboParent">
            <div class="app__form-item">
                <label class="app__form-label">
                    بازه زمانی
                </label>
                <div>
                    @{ Html.RenderPartial("~/Views/PreventiveMaintenancesSchedulingReport/FilterForm/FilterFormDateCombo.cshtml");}
                </div>
                <div class="app__form-error app__hide" id="filterFormDateComboError">
                    بازه زمانی انتخاب نشده است
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-md-3 app__hide" id="filterFormPeriodStartDatePickerParent">
            <div class="app__form-item">
                <label class="app__form-label">
                    از تاریخ
                </label>
                <div>
                    <input type="text" class="app__form-datepicker"
                           id="filterFormPeriodStartDatePicker"
                           placeholder="از تاریخ"
                           data-mddatetimepicker="true"
                           data-englishnumber="true"
                           data-targetdateselector="#filterFormPeriodStartDatePicker" />
                </div>
                <div class="app__form-error app__hide" id="filterFormPeriodStartDatePickerError">
                    شروع بازه زمانی انتخاب نشده است
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-md-3 app__hide" id="filterFormPeriodEndDatePickerParent">
            <div class="app__form-item">
                <label class="app__form-label">
                    تا تاریخ
                </label>
                <div>
                    <input type="text" class="app__form-datepicker"
                           id="filterFormPeriodEndDatePicker"
                           placeholder="تا تاریخ"
                           data-mddatetimepicker="true"
                           data-englishnumber="true"
                           data-targetdateselector="#filterFormPeriodEndDatePicker" />
                </div>
                <div class="app__form-error app__hide" id="filterFormPeriodEndDatePickerError">
                    پایان بازه زمانی انتخاب نشده است
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-md-2 app__hide" id="filterFormWeekNumberSpinEditParent">
            <div class="app__form-item">
                <label class="app__form-label">
                    شماره هفته
                </label>
                <div>
                    @Html.DevExpress().SpinEdit(settings =>
                    {
                        settings.Name = "filterFormWeekNumberSpinEdit";
                        settings.Properties.NullText = "شماره هفته را وارد کنید";
                        settings.Properties.MaxValue = 100000000;
                        settings.Properties.MinValue = 0;
                        settings.Properties.ShowOutOfRangeWarning = false;
                    }).GetHtml()
                </div>
                <div class="app__form-error app__hide" id="filterFormWeekNumberSpinEditError">
                    شماره هفته انتخاب نشده است
                </div>
            </div>
        </div>
        <div class="col-xs-5 col-md-2 pull-left filter-form__action-wrapper">
            @Html.DevExpress().Button(settings =>
            {
                settings.Name = "filterFormSearchBtn";
                settings.Text = "مشاهده";
                settings.UseSubmitBehavior = false;
                settings.EnableClientSideAPI = true;
                settings.Styles.CssPostfix = "filter-form__btn";
                settings.Width = Unit.Percentage(100);
                settings.ClientSideEvents.Click =
               "motorsazanClient.preventiveMaintenancesSchedulingReport.handleFilterFormGetPreventiveMaintenanceSchedulingListByConditionClick";
            }).GetHtml()
        </div>
    </div>
</div>

Motorsazan.CMMS.Client/Views/PreventiveMaintenancesSchedulingReport/FilterForm/FilterFormDateCombo.cshtml
@using Motorsazan.CMMS.Shared.Enums
@Html.DevExpress().ComboBox(
settings =>
{
    settings.Name = "filterFormDateCombo";
    settings.Width = Unit.Percentage(100);
    settings.Properties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.None;
    settings.Properties.NullText = "بازه زمانی را انتخاب کنید";
    settings.SelectedIndex = -1;
    settings.Properties.CallbackPageSize = 100;
    settings.Properties.IncrementalFilteringMode = IncrementalFilteringMode.Contains;
    settings.Properties.IncrementalFilteringDelay = 200;
    settings.SettingsLoadingPanel.Text = "در حال دریافت اطلاعات";

    settings.Properties.DropDownHeight = Unit.Pixel(310);


    settings.Properties.Items.Add("روز قبل", DatePeriodType.Yesterday);
    settings.Properties.Items.Add("روزجاری", DatePeriodType.CurrentDay);
    settings.Properties.Items.Add("یک هفته اخیر", DatePeriodType.RecentWeek);
    settings.Properties.Items.Add("یک ماه اخیر", DatePeriodType.RecentMonth);
    settings.Properties.Items.Add("سه ماه اخیر", DatePeriodType.RecentThreeMonths);
    settings.Properties.Items.Add("شش ماه اخیر", DatePeriodType.RecentSixMonths);
    settings.Properties.Items.Add("از ابتدای سال", DatePeriodType.ThisYear);
    settings.Properties.Items.Add("بازه زمانی خاص", DatePeriodType.CustomPeriod);
    settings.Properties.Items.Add("هفته خاص", "CustomWeek");

    settings.Properties.ClientSideEvents.SelectedIndexChanged =
        "motorsazanClient.preventiveMaintenancesSchedulingReport.handleFilterFormDateComboSelectedIndexChange";
}).GetHtml()

Motorsazan.CMMS.Client/Views/PreventiveMaintenancesSchedulingReport/FilterForm/FilterFormMainDepartmentCombo.cshtml
@model Motorsazan.CMMS.Shared.Models.Output.Inspection.OutputGetAllMainDepartment[]

@Html.DevExpress().ComboBox(
    settings =>
    {
        settings.Name = "filterFormMainDepartmentCombo";
        settings.CallbackRouteValues = new { Controller = "PreventiveMaintenancesScheduling", Action = "FilterFormMainDepartmentCombo" };
        settings.Width = Unit.Percentage(100);
        settings.Properties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.None;
        settings.Properties.NullText = "امور را وارد نمایید";
        settings.SelectedIndex = -1;
        settings.Properties.CallbackPageSize = 100;
        settings.Properties.IncrementalFilteringMode = IncrementalFilteringMode.Contains;
        settings.Properties.IncrementalFilteringDelay = 200;
        settings.SettingsLoadingPanel.Text = "در حال دریافت اطلاعات";

        settings.Properties.ValueField = "DepartmentId";
        settings.Properties.ValueType = typeof(int);

        settings.Properties.Columns.Add("Title", "نام امور");

        settings.Properties.ClientSideEvents.SelectedIndexChanged =
            "motorsazanClient.preventiveMaintenancesSchedulingReport.handleFilterFormMainDepartmentComboSelectedIndexChange";

    }).BindList(Model).GetHtml()

Motorsazan.CMMS.Client/Views/PreventiveMaintenancesSchedulingReport/FilterForm/FilterFormMaintenanceGroupCombo.cshtml
@model Motorsazan.CMMS.Shared.Models.Output.ProductiveWorkOrder.OutputGetMaintenanceGroupList[]

@Html.DevExpress().ComboBox(
    settings =>
    {
        settings.Name = "filterFormMaintenanceGroupCombo";
        settings.CallbackRouteValues = new { Controller = "PreventiveMaintenancesScheduling", Action = "FilterFormMaintenanceGroupCombo" };
        settings.Width = Unit.Percentage(100);
        settings.Properties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.None;
        settings.Properties.NullText = "گروه تعمیراتی را وارد نمایید";
        settings.SelectedIndex = -1;
        settings.Properties.CallbackPageSize = 100;
        settings.Properties.IncrementalFilteringMode = IncrementalFilteringMode.Contains;
        settings.Properties.IncrementalFilteringDelay = 200;
        settings.SettingsLoadingPanel.Text = "در حال دریافت اطلاعات";


        settings.Properties.ValueField = "MaintenanceGroupId";
        settings.Properties.ValueType = typeof(long);

        settings.Properties.Columns.Add("MaintenanceGroupName", "نام گروه تعمیراتی");


    }).BindList(Model).GetHtml()

Motorsazan.CMMS.Client/Views/PreventiveMaintenancesSchedulingReport/FilterForm/FilterFormSubDepartmentCombo.cshtml
@model Motorsazan.CMMS.Shared.Models.Output.Inspection.OutputGetSubDepartmentListHasMachineByMainDepartmentId[]

@Html.DevExpress().ComboBox(
    settings =>
    {
        settings.Name = "filterFormSubDepartmentCombo";
        settings.CallbackRouteValues = new { Controller = "PreventiveMaintenancesScheduling", Action = "FilterFormSubDepartmentCombo" };
        settings.Width = Unit.Percentage(100);
        settings.Properties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.None;
        settings.Properties.NullText = "خط را وارد نمایید";
        settings.SelectedIndex = -1;
        settings.Properties.CallbackPageSize = 100;
        settings.Properties.IncrementalFilteringMode = IncrementalFilteringMode.Contains;
        settings.Properties.IncrementalFilteringDelay = 200;
        settings.SettingsLoadingPanel.Text = "در حال دریافت اطلاعات";


        settings.Properties.ValueField = "DepartmentId";
        settings.Properties.ValueType = typeof(int);

        settings.Properties.Columns.Add("Title", "نام خط");

        settings.Properties.ClientSideEvents.BeginCallback = "motorsazanClient.preventiveMaintenancesSchedulingReport.handleFilterFormSubDepartmentComboBeginCallback";

    }).BindList(Model).GetHtml()